issuetracking/urls.py
from django.conf.urls.defaults import patterns, url, include

from issuetracking.views import ProjectListView, ProjectDetailView, IssueDetailView


urlpatterns = patterns('',
    url(r'^', include(patterns('', 
        url(r'^$', ProjectListView.as_view(), name="project_list"),
        url(r'^(?P<slug>[^/]+)/$', ProjectDetailView.as_view(), name="project_detail"),
        url(r'^(?P<project_slug>[^/]+)/(?P<pk>\d+)/$', IssueDetailView.as_view(), name="issue_detail"),
    ), app_name="issuetracking", namespace="issuetracking"))
)

issuetracking/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group

from taggit.managers import TaggableManager


class Project(models.Model):
    title = models.CharField(verbose_name=_("title"), max_length=100)
    slug = models.SlugField(verbose_name=_("slug"))
    subtitle = models.CharField(verbose_name=_("sub-title"), max_length=100, blank=True)
    description = models.TextField(verbose_name=_("description"), blank=True)
    group = models.ForeignKey(Group, verbose_name=_("user group"), related_name="projects")
    
    class Meta:
        verbose_name = _("project")
        verbose_name_plural = _("projects")
    
    def __unicode__(self):
        return u"%s" % (self.title,)


class Issue(models.Model):
    STATUS_NEW = 1
    STATUS_ASSIGNED = 2
    STATUS_RESOLVED = 3
    STATUS_CLOSED = 4
    STATUS_CHOICES = (
        (STATUS_NEW, _("new")),
        (STATUS_ASSIGNED, _("assigned")),
        (STATUS_RESOLVED, _("resolved")),
        (STATUS_CLOSED, _("closed")),
    )
    
    project = models.ForeignKey(Project, verbose_name=_("project"), related_name="issues")
    title = models.CharField(verbose_name=_("title"), max_length=255)
    description = models.TextField(verbose_name=_("description"), blank=True)
    status = models.PositiveSmallIntegerField(verbose_name=_("status"), choices=STATUS_CHOICES, default=STATUS_NEW)
    reported_by = models.ForeignKey(User, verbose_name=_("reported by"), related_name="reported_issues")
    assigned_to = models.ForeignKey(User, verbose_name=_("assigned to"), related_name="assigned_issues", blank=True, null=True)
    tags = TaggableManager()
    
    class Meta:
        verbose_name = _("issue")
        verbose_name_plural = _("issues")
    
    def __unicode__(self):
        return u"%s" % (self.title,)
    
    def save(self, *args, **kwargs):
        if self.status == self.STATUS_NEW and self.assigned_to:
            self.status = self.STATUS_ASSIGNED
        super(Issue, self).save(*args, **kwargs)

issuetracking/views.py
from django.views.generic import ListView, DetailView

from issuetracking.models import Project, Issue


class ProjectMixin(object):
    model = Project


class IssueMixin(object):
    model = Issue


class ProjectListView(ProjectMixin, ListView):
    context_object_name = "project_list"


class ProjectDetailView(ProjectMixin, DetailView):
    context_object_name = "project"


class IssueDetailView(IssueMixin, DetailView):
    context_object_name = "issue"

issuetracking/templates/issuetracking/issue_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
    <h1>{{ issue.project.title }}</h1>
    {% if issue.project.subtitle %}<h2>{{ issue.project.subtitle }}</h2>{% endif %}
    
    <dl>
        <dt>{% trans "status"|capfirst %}</dt>
        <dd>{{ issue.get_status_display }}</dd>
        <dt>{% trans "reported by"|capfirst %}</dt>
        <dd>{{ issue.reported_by }}</dd>
        <dt>{% trans "assigned to"|capfirst %}</dt>
        <dd>{{ issue.assigned_to }}</dd>
    </dl>
    
    <h3>{{ issue.title }}</h3>
    {% if issue.description %}{{ issue.description|linebreaks }}{% endif %}
    
{% endblock %}

issuetracking/templates/issuetracking/project_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
    <h1>{{ project.title }}</h1>
    {% if project.subtitle %}<h2>{{ project.subtitle }}</h2>{% endif %}
    {% if project.description %}{{ project.description|linebreaks }}{% endif %}
    
    {% if project.issues.count %}
        <table class="issues">
            <thead>
                <th>{% trans "title"|capfirst %}</th>
                <th>{% trans "status"|capfirst %}</th>
                <th>{% trans "reported by"|capfirst %}</th>
                <th>{% trans "assigned to"|capfirst %}</th>
                <th>{% trans "tags"|capfirst %}</th>
            </thead>
            <tbody>
                {% for issue in project.issues.all %}
                    <tr>
                        <th><a href="{% url 'issuetracking:issue_detail' project.slug issue.id %}">{{ issue.title }}</a></th>
                        <td>{{ issue.get_status_display }}</td>
                        <td>{{ issue.reported_by }}</td>
                        <td>{{ issue.assigned_to }}</td>
                        <td>{{ issue.tags.all|join:", " }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </ul>
    {% endif %}
{% endblock %}

issuetracking/templates/issuetracking/project_list.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
    <h1>{% trans "Projects" %}</h1>
    
    {% if project_list|length %}
        <ul>
            {% for project in project_list %}
                <li><a href="{% url 'issuetracking:project_detail' project.slug %}">{{ project.title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}